@echo off
echo Stopping running processes...
taskkill /f /im node.exe >nul 2>&1

echo Clearing Next.js cache...
if exist .next rmdir /s /q .next

echo Installing dependencies...
npm install

echo Starting the application...
npm run dev 